apiVersion: v1
kind: Service
metadata:
  name: dr-program
  namespace: gridforge
  labels: { app.kubernetes.io/name: dr-program, gridforge.io/domain: derms }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50142, targetPort: 50142 }]
  selector: { app.kubernetes.io/name: dr-program }
