apiVersion: v1
kind: ConfigMap
metadata:
  name: tamper-detection
  namespace: gridforge
  labels: { app.kubernetes.io/name: tamper-detection, gridforge.io/domain: ami }
data:
  LOG_LEVEL: info
  PORT: "50103"
