apiVersion: v1
kind: Service
metadata:
  name: {{ include "bill-service.fullname" . }}
  labels: {{- include "bill-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - { port: {{ .Values.service.port }}, targetPort: http, protocol: TCP, name: http }
  selector: {{- include "bill-service.selectorLabels" . | nindent 4 }}
