apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata: { name: gridforge, namespace: flux-system }
spec:
  interval: 1m
  url: https://github.com/prabhat-roy/GridForge.git
  ref: { branch: main }
